# Run source checks.
name: source_checks
on:
  pull_request:
  push:
permissions: read-all
jobs:
  asan:
    name: Check source with asan
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-24.04
          compiler: 'gcc'
          configure_options: '--enable-asan'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
    - name: Install build dependencies
      run: |
        sudo apt -y install autoconf automake autopoint build-essential git libasan8 libtool pkg-config
    - name: Download test data
      run: |
        if test -x "synctestdata.sh"; then ./synctestdata.sh; fi
    - name: Building from source
      env:
        CC: ${{ matrix.compiler }}
      run: |
        tests/build.sh ${{ matrix.configure_options }}
    - name: Run tests
      run: |
        make check CHECK_WITH_ASAN=1 CHECK_WITH_STDERR=1
  ubsan:
    name: Check source with ubsan
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-24.04
          compiler: 'gcc'
          configure_options: '--enable-ubsan'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
    - name: Install build dependencies
      run: |
        sudo apt -y install autoconf automake autopoint build-essential git libtool libubsan1 pkg-config
    - name: Download test data
      run: |
        if test -x "synctestdata.sh"; then ./synctestdata.sh; fi
    - name: Building from source
      env:
        CC: ${{ matrix.compiler }}
      run: |
        tests/build.sh ${{ matrix.configure_options }}
    - name: Run tests
      run: |
        make check CHECK_WITH_STDERR=1
